name: Run Tests
on:
  push:
    branches: ["main"]

jobs:
  execute_tests:
    name: "Install requirements and execute tests"
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: desafio2.settings
        run: pytest
